apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: openshift-gitops
spec:
  destination:
    namespace: app2
    server: https://kubernetes.default.svc
  project: default
  #project: one
  source:
    path: app2/
    repoURL: https://github.com/abavage/argo-deployment
    targetRevision: main
  syncPolicy:
    automated:
      #prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
